[profile.nvidia-54]   # choose the profile you want here 1G
num_displays = 1
display_width = 1920
display_height = 1080
max_pixels = 2073600
framebuffer = 0x38000000
framebuffer_reservation = 0x8000000

[vm.100]
frl_enabled = 0

